# Generated by Django 2.0.7 on 2019-04-12 14:29

import course.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=10)),
                ('related_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('reladed_levels', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, size=None)),
                ('ordering_code', models.IntegerField(default=0)),
                ('medium', models.CharField(choices=[('bn', 'Bangla'), ('en', 'English'), ('ar', 'Arabi')], default='bn', max_length=3)),
                ('description', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('image', models.ImageField(blank=True, default='default.jpg', height_field='height_field', null=True, upload_to=course.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.Level')),
            ],
            options={
                'ordering': ['level', 'ordering_code', 'code', 'name'],
            },
        ),
    ]
